[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[dependencies]
exitcode = "1.1.2"
clap = { version = "3.0", features = ["derive"]}
codespan-reporting = "0.11.1"
lang = { path = "../lang" }

 [[bin]]
name = "stark"
path = "src/stark/main.rs"