extern printi(val: int): void

// Add
var1: int = 1 + 2
printi(var1)

// Sub
var2: int = 2 - 1
printi(var2)

// Mul
var3: int = 2 * 2
printi(var3)

// Div
var4: int = 6 / 2
printi(var4)

// Complex operation
var5: int = ((6 / 2 ) * 3) - 1
printi(var5)

// Multiple variables usage
var6: int = 3 + 2
var7: int = 4 * 2
printi(var7 + 1)
printi(var6 + var7)
var8: int = var6 + var7
printi(var8)

// Bool operators
var9: bool = true && false
var10: bool = true || false

// Comparisons
var11: bool = (1 == 1)
var12: bool = (1.0 != 1.0)
var13: bool = (true != false)